In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')
df['split'] = np.random.randn(df.shape[0], 1)

msk = np.random.rand(len(df)) <= 0.7

train = df[msk]
test = df[~msk]

In [2]:
train.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9  ...  X171  X172  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33  ...   -15   -31   
1  X15.V1.924  386  382  356  331  320  315  307  272  244  ...   150   146   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85  ...    64    48   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87  ...   -81   -80   
5   X14.V1.56   55   28   18   16   16   19   25   40   52  ...   -31   -42   

   X173  X174  X175  X176  X177  X178  y     split  
0   -77  -103  -127  -116   -83   -51  4  0.241879  
1   152   157   156   154   143   129  1 -0.539569  
2    19   -12   -30   -35   -35   -36  5 -0.312207  
3   -77   -85   -77   -72   -69   -65  5 -0.753444  
5   -54   -60   -64   -60   -56   -55  5 -1.157492  

[5 rows x 181 columns]

In [3]:
train = train.drop(columns = ['Unnamed: 0'], axis = 1)

In [4]:
train.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...  X171  X172  X173  \
0  135  190  229  223  192  125   55   -9  -33  -38  ...   -15   -31   -77   
1  386  382  356  331  320  315  307  272  244  232  ...   150   146   152   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  ...    64    48    19   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  ...   -81   -80   -77   
5   55   28   18   16   16   19   25   40   52   66  ...   -31   -42   -54   

   X174  X175  X176  X177  X178  y     split  
0  -103  -127  -116   -83   -51  4  0.241879  
1   157   156   154   143   129  1 -0.539569  
2   -12   -30   -35   -35   -36  5 -0.312207  
3   -85   -77   -72   -69   -65  5 -0.753444  
5   -60   -64   -60   -56   -55  5 -1.157492  

[5 rows x 180 columns]

In [5]:
test = test.drop(columns = ['Unnamed: 0'], axis = 1)

In [6]:
test.head()

X1  X2  X3   X4   X5   X6   X7   X8  X9  X10  ...  X171  X172  X173  X174  \
4   -9 -65 -98 -102  -78  -48  -16    0 -21  -59  ...     2   -12   -32   -41   
6  -55  -9  52  111  135  129  103   72  37    0  ...   -99   -79   -62   -41   
9    8  15  13    3   -6   -8   -5    4  25   41  ...    31    11    -5   -17   
10  -5  15  28   28    9  -29  -41  -19  14   30  ...    -4    25    16   -16   
19   4  24  51   76   92  102  104  101  90   80  ...     5    10    19    31   

    X175  X176  X177  X178  y     split  
4    -65   -83   -89   -73  5  0.698558  
6    -26    11    67   128  4 -2.114769  
9    -19   -15   -15   -11  4  1.115289  
10   -74  -101   -89   -49  5  0.964211  
19    36    40    43    36  2 -0.030538  

[5 rows x 180 columns]

In [10]:
#train = pd.DataFrame(train)
#train = train.to_csv(r'DataTrain.csv', index= False)
#train = pd.DataFrame(train)

In [7]:
from sklearn.preprocessing import MinMaxScaler
#train.head()

In [8]:
scaler = MinMaxScaler()
fit = scaler.fit_transform(train)
print(fit)

[[0.62607041 0.63494051 0.66387906 ... 0.47489316 0.75       0.52642107]
 [0.70567713 0.69505322 0.70472821 ... 0.52297009 0.         0.42499177]
 [0.57310498 0.56324358 0.57510454 ... 0.47889957 1.         0.45450258]
 ...
 [0.58769426 0.5773325  0.58604053 ... 0.48637821 1.         0.36269163]
 [0.57056771 0.5676268  0.58732711 ... 0.50320513 0.5        0.30287279]
 [0.59245163 0.58829054 0.60855581 ... 0.49385684 0.75       0.40290727]]


C:\Users\HCL\AppData\Local\Continuum\anaconda4\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [9]:
trans_cs  = pd.DataFrame(fit)
trans_cs.head()
#trans_csv = trans.to_csv(r'DataTrain.csv', index = False)

0         1         2         3         4         5         6    \
0  0.626070  0.634941  0.663879  0.673396  0.599275  0.526728  0.486466   
1  0.705677  0.695053  0.704728  0.708564  0.637957  0.579905  0.551431   
2  0.573105  0.563244  0.575105  0.588733  0.531581  0.481668  0.457592   
3  0.549952  0.543832  0.559344  0.570824  0.514355  0.465155  0.445991   
4  0.600698  0.584220  0.596012  0.605992  0.546086  0.497061  0.478732   

        7         8         9    ...       170       171       172       173  \
0  0.462484  0.464883  0.467297  ...  0.564369  0.544073  0.521051  0.489858   
1  0.535948  0.536146  0.536280  ...  0.614704  0.603850  0.593542  0.562101   
2  0.445752  0.451505  0.452989  ...  0.588469  0.570753  0.551440  0.515143   
3  0.438693  0.450990  0.456822  ...  0.544234  0.527524  0.521051  0.494860   
4  0.475294  0.486751  0.493868  ...  0.559487  0.540358  0.528332  0.501806   

        174       175       176       177   178       179  
0  0.454331  0.434953  0.435612  0.474893  0.75  0.526421  
1  0.528396  0.505486  0.495495  0.522970  0.00  0.424992  
2  0.479717  0.456113  0.448331  0.478900  1.00  0.454503  
3  0.467417  0.446447  0.439322  0.471154  1.00  0.397232  
4  0.470819  0.449582  0.442766  0.473825  1.00  0.344788  

[5 rows x 180 columns]

In [10]:
trans_to_train_csv = trans_cs.to_csv(r'DtataTrain.csv', index = False)

In [12]:
fit_test = scaler.fit_transform(test)
print(fit_test)

[[0.49000588 0.46574519 0.46862049 ... 0.49231307 1.         0.56883782]
 [0.47648442 0.48257212 0.51302546 ... 0.56254368 0.75       0.20502121]
 [0.49500294 0.48978365 0.50148017 ... 0.51397624 0.75       0.62272895]
 ...
 [0.4861846  0.46604567 0.46181172 ... 0.49650594 0.         0.4938892 ]
 [0.48471487 0.46935096 0.47276495 ... 0.51362683 0.         0.26196519]
 [0.4861846  0.47866587 0.49082297 ... 0.50104822 0.25       0.35519216]]


C:\Users\HCL\AppData\Local\Continuum\anaconda4\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [13]:
trans_cs_test  = pd.DataFrame(fit)
trans_cs_test.head()

0         1         2         3         4         5         6    \
0  0.626070  0.634941  0.663879  0.673396  0.599275  0.526728  0.486466   
1  0.705677  0.695053  0.704728  0.708564  0.637957  0.579905  0.551431   
2  0.573105  0.563244  0.575105  0.588733  0.531581  0.481668  0.457592   
3  0.549952  0.543832  0.559344  0.570824  0.514355  0.465155  0.445991   
4  0.600698  0.584220  0.596012  0.605992  0.546086  0.497061  0.478732   

        7         8         9    ...       170       171       172       173  \
0  0.462484  0.464883  0.467297  ...  0.564369  0.544073  0.521051  0.489858   
1  0.535948  0.536146  0.536280  ...  0.614704  0.603850  0.593542  0.562101   
2  0.445752  0.451505  0.452989  ...  0.588469  0.570753  0.551440  0.515143   
3  0.438693  0.450990  0.456822  ...  0.544234  0.527524  0.521051  0.494860   
4  0.475294  0.486751  0.493868  ...  0.559487  0.540358  0.528332  0.501806   

        174       175       176       177   178       179  
0  0.454331  0.434953  0.435612  0.474893  0.75  0.526421  
1  0.528396  0.505486  0.495495  0.522970  0.00  0.424992  
2  0.479717  0.456113  0.448331  0.478900  1.00  0.454503  
3  0.467417  0.446447  0.439322  0.471154  1.00  0.397232  
4  0.470819  0.449582  0.442766  0.473825  1.00  0.344788  

[5 rows x 180 columns]

In [14]:
trans_to_test_csv = trans_cs_test.to_csv(r'DtataTest.csv', index = False)